export const SERVICES = [
  "Amazon",
  "Blablacar",
  "Bolt",
  "Ebay",
  "Fiverr",
  "Google",
  "Hinge",
  "Microsoft",
  "Paypal",
  "Proton",
  "Steam",
  "Telegram",
  "Tinder",
  "Uber",
  "Walt",
  "Wechat",
  "Whatsapp",
  "Yahoo",
] as const

export const COUNTRIES = [
  "Algeria",
  "Argentina",
  "Australia",
  "Austria",
  "Belgium",
  "Brazil",
  "Bulgaria",
  "Canada",
  "Chile",
  "China",
  "Colombia",
  "Croatia",
  "Czech Republic",
  "Denmark",
  "Egypt",
  "Finland",
  "France",
  "Germany",
  "Greece",
  "Hungary",
  "India",
  "Indonesia",
  "Ireland",
  "Israel",
  "Italy",
  "Japan",
  "Kenya",
  "Malaysia",
  "Mexico",
  "Morocco",
  "Netherlands",
  "New Zealand",
  "Nigeria",
  "Norway",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Romania",
  "Saudi Arabia",
  "Singapore",
  "Slovakia",
  "South Africa",
  "South Korea",
  "Spain",
  "Sweden",
  "Switzerland",
  "Thailand",
  "Tunisia",
  "Turkey",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Venezuela",
  "Vietnam",
] as const

export const PROXIES = [
  "ProxyAFR-Secure-01",
  "ProxyAFR-Secure-02",
  "ProxyASIA-Fast-01",
  "ProxyASIA-Fast-02",
  "ProxyASIA-Fast-03",
  "ProxyDedicated-High-01",
  "ProxyDedicated-High-02",
  "ProxyEU-Premium-01",
  "ProxyEU-Premium-02",
  "ProxyEU-Premium-03",
  "ProxyLATAM-Speed-01",
  "ProxyLATAM-Speed-02",
  "ProxyMobile-Global-01",
  "ProxyMobile-Global-02",
  "ProxyResidence-DE-01",
  "ProxyResidence-ES-01",
  "ProxyResidence-ES-02",
  "ProxyResidence-FR-01",
  "ProxyResidence-IT-01",
  "ProxyResidence-IT-02",
  "ProxyResidence-UK-01",
  "ProxyUS-Elite-01",
  "ProxyUS-Elite-02",
  "ProxyUS-Elite-03",
] as const
